services:
  mysql:
    hostname: my-db
    image: mysql
    container_name: mysql_container
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
#    platform: linux/arm64, linux/amd64
    volumes:
      - my-sql-volume:/var/lib/mysql
volumes:
  my-sql-volume:
    name: volume-mysql