services:
  mysql:
    image: mysql
    container_name: mysql_container
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
#    platform: linux/arm64, linux/amd64
    volumes:
      - my-sql-volume:/var/lib/mysql
  redis:
    image: redis
    container_name: redis_container
    restart: always
    ports:
      - 6379:6379
volumes:
  my-sql-volume:
    name: volume-mysql